#ifndef COMMANDEXECUTIONRESULT_CODES_H
#define COMMANDEXECUTIONRESULT_CODES_H

const int RESULT_OK = 0;
const int COMMAND_NOT_FOUND = -1;
const int MISSING_PARAMETER = -2;
const int TOOMUCH_PARAMETERS = -3;
const int TOOMUCH_NUMBER_OF_POINTS_PER_SWEEP = -4;
const int NOT_ENOUGH_NUMBER_OF_POINTS_PER_SWEEP = -5;
const int START_VOLTAGE_GREATER_THAN_MAX_VOLTAGE = -6;
const int STOP_VOLTAGE_GREATER_THAN_MAX_VOLTAGE = -7;
const int NPLC_GREATER_THAN_MAX_VALUE = -8;
const int NPLC_LOWER_THAN_MIN_VALUE = -9;

#endif // COMMANDEXECUTIONRESULT_CODES_H
